// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rqmTJ9WSF4RQaQFCvo2iUX
// Component: NQ_NX6MhhQIl

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_fragment_design_system_css from "../paziresh_24_design_system/plasmic_paziresh_24_design_system.module.css"; // plasmic-import: h9Dbk9ygddw7UVEq1NNhKi/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: rqmTJ9WSF4RQaQFCvo2iUX/projectcss
import sty from "./Plasmicاطلاعاتشخصبمار.module.css"; // plasmic-import: NQ_NX6MhhQIl/css

createPlasmicElementProxy;

export type Plasmicاطلاعاتشخصبمار__VariantMembers = {
  transparent: "transparent";
  succses: "succses";
};
export type Plasmicاطلاعاتشخصبمار__VariantsArgs = {
  transparent?: SingleBooleanChoiceArg<"transparent">;
  succses?: SingleBooleanChoiceArg<"succses">;
};
type VariantPropType = keyof Plasmicاطلاعاتشخصبمار__VariantsArgs;
export const Plasmicاطلاعاتشخصبمار__VariantProps = new Array<VariantPropType>(
  "transparent",
  "succses"
);

export type Plasmicاطلاعاتشخصبمار__ArgsType = {
  value?: string;
  label?: string;
};
type ArgPropType = keyof Plasmicاطلاعاتشخصبمار__ArgsType;
export const Plasmicاطلاعاتشخصبمار__ArgProps = new Array<ArgPropType>(
  "value",
  "label"
);

export type Plasmicاطلاعاتشخصبمار__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultاطلاعاتشخصبمارProps {
  value?: string;
  label?: string;
  transparent?: SingleBooleanChoiceArg<"transparent">;
  succses?: SingleBooleanChoiceArg<"succses">;
  className?: string;
}

const $$ = {};

function Plasmicاطلاعاتشخصبمار__RenderFunc(props: {
  variants: Plasmicاطلاعاتشخصبمار__VariantsArgs;
  args: Plasmicاطلاعاتشخصبمار__ArgsType;
  overrides: Plasmicاطلاعاتشخصبمار__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "transparent",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.transparent
      },
      {
        path: "succses",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.succses
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_fragment_design_system_css.plasmic_tokens,
        sty.root,
        {
          [sty.roottransparent]: hasVariant(
            $state,
            "transparent",
            "transparent"
          )
        }
      )}
      dir={"rtl"}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__yuhil,
          {
            [sty.texttransparent__yuhil0A1Tb]: hasVariant(
              $state,
              "transparent",
              "transparent"
            )
          }
        )}
      >
        <React.Fragment>
          {(() => {
            try {
              return $props.label;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return "\u0646\u0627\u0645 \u0648 \u0646\u0627\u0645 \u062e\u0627\u0646\u0648\u0627\u062f\u06af\u06cc :";
              }
              throw e;
            }
          })()}
        </React.Fragment>
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__ciWnO,
          {
            [sty.textsuccses__ciWnOOzdWd]: hasVariant(
              $state,
              "succses",
              "succses"
            )
          }
        )}
      >
        <React.Fragment>
          {(() => {
            try {
              return $props.value;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return "\u0622\u06cc\u062f\u0627 \u0627\u0631\u062f\u0627\u0646\u06cc";
              }
              throw e;
            }
          })()}
        </React.Fragment>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  Plasmicاطلاعاتشخصبمار__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: Plasmicاطلاعاتشخصبمار__VariantsArgs;
    args?: Plasmicاطلاعاتشخصبمار__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<Plasmicاطلاعاتشخصبمار__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      Plasmicاطلاعاتشخصبمار__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: Plasmicاطلاعاتشخصبمار__ArgProps,
          internalVariantPropNames: Plasmicاطلاعاتشخصبمار__VariantProps
        }),
      [props, nodeName]
    );
    return Plasmicاطلاعاتشخصبمار__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName =
      "Plasmic\u0627\u0637\u0644\u0627\u0639\u0627\u062a\u0634\u062e\u0635\u0628\u0645\u0627\u0631";
  } else {
    func.displayName = `Plasmicاطلاعاتشخصبمار.${nodeName}`;
  }
  return func;
}

export const Plasmicاطلاعاتشخصبمار = Object.assign(
  // Top-level Plasmicاطلاعاتشخصبمار renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for Plasmicاطلاعاتشخصبمار
    internalVariantProps: Plasmicاطلاعاتشخصبمار__VariantProps,
    internalArgProps: Plasmicاطلاعاتشخصبمار__ArgProps
  }
);

export default Plasmicاطلاعاتشخصبمار;
/* prettier-ignore-end */
