// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rqmTJ9WSF4RQaQFCvo2iUX
// Component: 2yLCE-L6JXEZ

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Checkbox from "../../Checkbox"; // plasmic-import: WT38Ke_Z_eCs/component
import Select from "../../Select"; // plasmic-import: OzXPMxUo1TiP/component
import { Popover } from "@plasmicpkgs/radix-ui";
import روزهاهفته from "../../\u0631\u0648\u0632\u0647\u0627\u0647\u0641\u062A\u0647"; // plasmic-import: oTc6QTbblo0F/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_fragment_design_system_css from "../paziresh_24_design_system/plasmic_paziresh_24_design_system.module.css"; // plasmic-import: h9Dbk9ygddw7UVEq1NNhKi/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: rqmTJ9WSF4RQaQFCvo2iUX/projectcss
import sty from "./Plasmicساعتار.module.css"; // plasmic-import: 2yLCE-L6JXEZ/css

import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: 9z2THf0LJcnY/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: ep-N6UwP60oB/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: j_DyRtM8QKgI/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: l5BVq9QEthSF/icon

createPlasmicElementProxy;

export type Plasmicساعتار__VariantMembers = {};
export type Plasmicساعتار__VariantsArgs = {};
type VariantPropType = keyof Plasmicساعتار__VariantsArgs;
export const Plasmicساعتار__VariantProps = new Array<VariantPropType>();

export type Plasmicساعتار__ArgsType = {
  checkboxIsChecked?: boolean;
  onCheckboxIsCheckedChange?: (val: boolean) => void;
  centerId?: string;
  listOfWorkhoureCopy?: any;
  onListOfWorkhoureCopyChange?: (val: string) => void;
  duration?: number;
  dayOfWeek?: number;
  endedSelectedDay?: (id: any) => void;
};
type ArgPropType = keyof Plasmicساعتار__ArgsType;
export const Plasmicساعتار__ArgProps = new Array<ArgPropType>(
  "checkboxIsChecked",
  "onCheckboxIsCheckedChange",
  "centerId",
  "listOfWorkhoureCopy",
  "onListOfWorkhoureCopyChange",
  "duration",
  "dayOfWeek",
  "endedSelectedDay"
);

export type Plasmicساعتار__OverridesType = {
  root?: Flex__<"div">;
  checkbox?: Flex__<typeof Checkbox>;
  to?: Flex__<typeof Select>;
  from?: Flex__<typeof Select>;
  popoverCore?: Flex__<typeof Popover>;
  روزهاهفته?: Flex__<typeof روزهاهفته>;
};

export interface DefaultساعتارProps {
  checkboxIsChecked?: boolean;
  onCheckboxIsCheckedChange?: (val: boolean) => void;
  centerId?: string;
  listOfWorkhoureCopy?: any;
  onListOfWorkhoureCopyChange?: (val: string) => void;
  duration?: number;
  dayOfWeek?: number;
  endedSelectedDay?: (id: any) => void;
  className?: string;
}

const $$ = {};

function Plasmicساعتار__RenderFunc(props: {
  variants: Plasmicساعتار__VariantsArgs;
  args: Plasmicساعتار__ArgsType;
  overrides: Plasmicساعتار__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "checkbox.isChecked",
        type: "writable",
        variableType: "boolean",

        valueProp: "checkboxIsChecked",
        onChangeProp: "onCheckboxIsCheckedChange"
      },
      {
        path: "to[].value",
        type: "private",
        variableType: "text"
      },
      {
        path: "from[].value",
        type: "private",
        variableType: "text"
      },
      {
        path: "popoverCore[].open",
        type: "private",
        variableType: "boolean"
      },
      {
        path: "selectedhoure",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => ({})
      },
      {
        path: "listOfWorkhoureCopy",
        type: "writable",
        variableType: "array",

        valueProp: "listOfWorkhoureCopy",
        onChangeProp: "onListOfWorkhoureCopyChange"
      },
      {
        path: "days",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => [
          { id: 6, name: "\u0634\u0646\u0628\u0647", nameEn: "Saturday" },
          {
            id: 7,
            name: "\u06cc\u06a9\u0634\u0646\u0628\u0647",
            nameEn: "Sunday"
          },
          {
            id: 1,
            name: "\u062f\u0648\u0634\u0646\u0628\u0647",
            nameEn: "Monday"
          },
          {
            id: 2,
            name: "\u0633\u0647\u200c\u0634\u0646\u0628\u0647",
            nameEn: "Tuesday"
          },
          {
            id: 3,
            name: "\u0686\u0647\u0627\u0631\u0634\u0646\u0628\u0647",
            nameEn: "Wednesday"
          },
          {
            id: 4,
            name: "\u067e\u0646\u062c\u200c\u0634\u0646\u0628\u0647",
            nameEn: "Thursday"
          },
          { id: 5, name: "\u062c\u0645\u0639\u0647", nameEn: "Friday" }
        ]
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_fragment_design_system_css.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__gc4JJ)}>
        <Checkbox
          data-plasmic-name={"checkbox"}
          data-plasmic-override={overrides.checkbox}
          className={classNames("__wab_instance", sty.checkbox)}
          isChecked={
            generateStateValueProp($state, ["checkbox", "isChecked"]) ?? false
          }
          onChange={(...eventArgs) => {
            generateStateOnChangeProp($state, ["checkbox", "isChecked"])(
              eventArgs[0]
            );
          }}
        >
          <React.Fragment>
            {(() => {
              try {
                return $state.days.find(day => day.id === $props.dayOfWeek)
                  .name;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "\u0634\u0646\u0628\u0647";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </Checkbox>
        <div className={classNames(projectcss.all, sty.freeBox__rz8Wp)} />
      </div>
      {(() => {
        try {
          return $state.checkbox.isChecked === true;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return false;
          }
          throw e;
        }
      })()
        ? (_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
            (() => {
              try {
                return $state.listOfWorkhoureCopy;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return [];
                }
                throw e;
              }
            })()
          ).map((__plasmic_item_0, __plasmic_idx_0) => {
            const currentItem = __plasmic_item_0;
            const currentIndex = __plasmic_idx_0;
            return (
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__syBra)}
                key={currentIndex}
              >
                {(() => {
                  const child$Props = {
                    className: classNames("__wab_instance", sty.to),
                    onChange: async (...eventArgs: any) => {
                      ((...eventArgs) => {
                        generateStateOnChangeProp($state, [
                          "to",
                          __plasmic_idx_0,
                          "value"
                        ])(eventArgs[0]);
                      }).apply(null, eventArgs);
                      (async value => {
                        const $steps = {};

                        $steps["updateListOfWorkhoureCopy"] = true
                          ? (() => {
                              const actionArgs = {
                                variable: {
                                  objRoot: $state,
                                  variablePath: ["listOfWorkhoureCopy"]
                                },
                                operation: 0,
                                value: (() => {
                                  let list = $state.listOfWorkhoureCopy;
                                  list[currentIndex].to =
                                    $state.to[currentIndex].value;
                                  return list;
                                })()
                              };
                              return (({
                                variable,
                                value,
                                startIndex,
                                deleteCount
                              }) => {
                                if (!variable) {
                                  return;
                                }
                                const { objRoot, variablePath } = variable;

                                $stateSet(objRoot, variablePath, value);
                                return value;
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["updateListOfWorkhoureCopy"] != null &&
                          typeof $steps["updateListOfWorkhoureCopy"] ===
                            "object" &&
                          typeof $steps["updateListOfWorkhoureCopy"].then ===
                            "function"
                        ) {
                          $steps["updateListOfWorkhoureCopy"] = await $steps[
                            "updateListOfWorkhoureCopy"
                          ];
                        }
                      }).apply(null, eventArgs);
                    },
                    options: (() => {
                      try {
                        return (() => {
                          const duration = $props.duration;
                          const options = [];
                          const initialHour = 21;
                          for (let i = 1; i <= 24; i++) {
                            const totalMinutes =
                              initialHour * 60 + i * duration;
                            const hour = Math.floor(totalMinutes / 60) % 24;
                            const minute = totalMinutes % 60;
                            const formattedHour = `${
                              hour < 10 ? "0" : ""
                            }${hour}`;
                            const formattedMinute = `${
                              minute < 10 ? "0" : ""
                            }${minute}`;
                            options.push(`${formattedHour}:${formattedMinute}`);
                          }
                          return options;
                        })();
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return [
                            { value: "option1", label: "Option 1" },
                            { value: "option2", label: "Option 2" }
                          ];
                        }
                        throw e;
                      }
                    })(),
                    placeholder: "\u06f2\u06f1:\u06f0\u06f0",
                    value: generateStateValueProp($state, [
                      "to",
                      __plasmic_idx_0,
                      "value"
                    ])
                  };

                  initializePlasmicStates(
                    $state,
                    [
                      {
                        name: "to[].value",
                        initFunc: ({ $props, $state, $queries }) =>
                          (() => {
                            try {
                              return currentItem.to;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()
                      }
                    ],
                    [__plasmic_idx_0]
                  );
                  return (
                    <Select
                      data-plasmic-name={"to"}
                      data-plasmic-override={overrides.to}
                      {...child$Props}
                    />
                  );
                })()}
                <Icon6Icon
                  className={classNames(projectcss.all, sty.svg__e7USu)}
                  role={"img"}
                />

                {(() => {
                  const child$Props = {
                    className: classNames("__wab_instance", sty.from),
                    onChange: async (...eventArgs: any) => {
                      ((...eventArgs) => {
                        generateStateOnChangeProp($state, [
                          "from",
                          __plasmic_idx_0,
                          "value"
                        ])(eventArgs[0]);
                      }).apply(null, eventArgs);
                      (async value => {
                        const $steps = {};

                        $steps["updateListOfWorkhoureCopy"] = true
                          ? (() => {
                              const actionArgs = {
                                variable: {
                                  objRoot: $state,
                                  variablePath: ["listOfWorkhoureCopy"]
                                },
                                operation: 0,
                                value: (() => {
                                  let list = $state.listOfWorkhoureCopy;
                                  list[currentIndex].from =
                                    $state.from[currentIndex].value;
                                  return list;
                                })()
                              };
                              return (({
                                variable,
                                value,
                                startIndex,
                                deleteCount
                              }) => {
                                if (!variable) {
                                  return;
                                }
                                const { objRoot, variablePath } = variable;

                                $stateSet(objRoot, variablePath, value);
                                return value;
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["updateListOfWorkhoureCopy"] != null &&
                          typeof $steps["updateListOfWorkhoureCopy"] ===
                            "object" &&
                          typeof $steps["updateListOfWorkhoureCopy"].then ===
                            "function"
                        ) {
                          $steps["updateListOfWorkhoureCopy"] = await $steps[
                            "updateListOfWorkhoureCopy"
                          ];
                        }
                      }).apply(null, eventArgs);
                    },
                    options: (() => {
                      try {
                        return (() => {
                          const duration = $props.duration;
                          const options = [];
                          const initialHour = 17;
                          for (let i = 1; i <= 24; i++) {
                            const totalMinutes =
                              initialHour * 60 + i * duration;
                            const hour = Math.floor(totalMinutes / 60) % 24;
                            const minute = totalMinutes % 60;
                            const formattedHour = `${
                              hour < 10 ? "0" : ""
                            }${hour}`;
                            const formattedMinute = `${
                              minute < 10 ? "0" : ""
                            }${minute}`;
                            options.push(`${formattedHour}:${formattedMinute}`);
                          }
                          return options;
                        })();
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return [];
                        }
                        throw e;
                      }
                    })(),
                    placeholder: "\u06f1\u06f7:\u06f0\u06f0",
                    value: generateStateValueProp($state, [
                      "from",
                      __plasmic_idx_0,
                      "value"
                    ])
                  };

                  initializePlasmicStates(
                    $state,
                    [
                      {
                        name: "from[].value",
                        initFunc: ({ $props, $state, $queries }) =>
                          (() => {
                            try {
                              return currentItem.from;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()
                      }
                    ],
                    [__plasmic_idx_0]
                  );
                  return (
                    <Select
                      data-plasmic-name={"from"}
                      data-plasmic-override={overrides.from}
                      {...child$Props}
                    />
                  );
                })()}
                {(() => {
                  try {
                    return currentIndex === 0;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return false;
                    }
                    throw e;
                  }
                })() ? (
                  <Icon2Icon
                    className={classNames(projectcss.all, sty.svg__mj5V1)}
                    onClick={async event => {
                      const $steps = {};

                      $steps["updateListOfWorkhoureCopy"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["listOfWorkhoureCopy"]
                              },
                              operation: 5,
                              value: {
                                from: $state.to[
                                  $state.listOfWorkhoureCopy.length - 1
                                ].value,
                                to: (() => {
                                  const toValue =
                                    $state.to[
                                      $state.listOfWorkhoureCopy.length - 1
                                    ].value;
                                  const duration = $props.duration;
                                  const newTime = new Date(
                                    `2000-01-01T${toValue}`
                                  );
                                  newTime.setMinutes(
                                    newTime.getMinutes() + duration
                                  );
                                  return newTime.toLocaleTimeString("en-Gb", {
                                    hour12: false,
                                    hour: "2-digit",
                                    minute: "2-digit"
                                  });
                                })()
                              }
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              const arr = $stateGet(objRoot, variablePath);
                              arr.push(value);
                              return arr;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateListOfWorkhoureCopy"] != null &&
                        typeof $steps["updateListOfWorkhoureCopy"] ===
                          "object" &&
                        typeof $steps["updateListOfWorkhoureCopy"].then ===
                          "function"
                      ) {
                        $steps["updateListOfWorkhoureCopy"] = await $steps[
                          "updateListOfWorkhoureCopy"
                        ];
                      }
                    }}
                    role={"img"}
                  />
                ) : null}
                {(() => {
                  try {
                    return currentIndex !== 0;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return true;
                    }
                    throw e;
                  }
                })() ? (
                  <Icon5Icon
                    className={classNames(projectcss.all, sty.svg__mlgMh)}
                    onClick={async event => {
                      const $steps = {};

                      $steps["updateListOfWorkhoureCopy"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["listOfWorkhoureCopy"]
                              },
                              operation: 6,
                              startIndex: (() => {
                                try {
                                  return currentIndex;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return undefined;
                                  }
                                  throw e;
                                }
                              })(),
                              deleteCount: 1
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              const arr = $stateGet(objRoot, variablePath);
                              arr.splice(startIndex, deleteCount);
                              return arr;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateListOfWorkhoureCopy"] != null &&
                        typeof $steps["updateListOfWorkhoureCopy"] ===
                          "object" &&
                        typeof $steps["updateListOfWorkhoureCopy"].then ===
                          "function"
                      ) {
                        $steps["updateListOfWorkhoureCopy"] = await $steps[
                          "updateListOfWorkhoureCopy"
                        ];
                      }
                    }}
                    role={"img"}
                  />
                ) : null}
                {(() => {
                  const child$Props = {
                    className: classNames("__wab_instance", sty.popoverCore),
                    onOpenChange: generateStateOnChangeProp($state, [
                      "popoverCore",
                      __plasmic_idx_0,
                      "open"
                    ]),
                    open: generateStateValueProp($state, [
                      "popoverCore",
                      __plasmic_idx_0,
                      "open"
                    ]),
                    overlay: (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__d9Vk8
                        )}
                      >
                        <روزهاهفته
                          data-plasmic-name={
                            "\u0631\u0648\u0632\u0647\u0627\u0647\u0641\u062a\u0647"
                          }
                          data-plasmic-override={overrides.روزهاهفته}
                          className={classNames(
                            "__wab_instance",
                            sty.روزهاهفته
                          )}
                          selectTrigger={async days => {
                            const $steps = {};

                            $steps["runEndedSelectedDay"] = true
                              ? (() => {
                                  const actionArgs = {
                                    eventRef: $props["endedSelectedDay"],
                                    args: [
                                      (() => {
                                        try {
                                          return days;
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return undefined;
                                          }
                                          throw e;
                                        }
                                      })()
                                    ]
                                  };
                                  return (({ eventRef, args }) => {
                                    return eventRef?.(...(args ?? []));
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["runEndedSelectedDay"] != null &&
                              typeof $steps["runEndedSelectedDay"] ===
                                "object" &&
                              typeof $steps["runEndedSelectedDay"].then ===
                                "function"
                            ) {
                              $steps["runEndedSelectedDay"] = await $steps[
                                "runEndedSelectedDay"
                              ];
                            }

                            $steps["updatePopoverCore0Open"] = true
                              ? (() => {
                                  const actionArgs = {
                                    variable: {
                                      objRoot: $state,
                                      variablePath: ["popoverCore", "0", "open"]
                                    },
                                    operation: 0,
                                    value: false
                                  };
                                  return (({
                                    variable,
                                    value,
                                    startIndex,
                                    deleteCount
                                  }) => {
                                    if (!variable) {
                                      return;
                                    }
                                    const { objRoot, variablePath } = variable;

                                    $stateSet(objRoot, variablePath, value);
                                    return value;
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["updatePopoverCore0Open"] != null &&
                              typeof $steps["updatePopoverCore0Open"] ===
                                "object" &&
                              typeof $steps["updatePopoverCore0Open"].then ===
                                "function"
                            ) {
                              $steps["updatePopoverCore0Open"] = await $steps[
                                "updatePopoverCore0Open"
                              ];
                            }
                          }}
                          selectedDay={(() => {
                            try {
                              return $props.dayOfWeek;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                        />
                      </div>
                    ),
                    themeResetClass: classNames(
                      projectcss.root_reset,
                      projectcss.plasmic_default_styles,
                      projectcss.plasmic_mixins,
                      projectcss.plasmic_tokens,
                      plasmic_fragment_design_system_css.plasmic_tokens
                    )
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "open",
                        plasmicStateName: "popoverCore[].open"
                      }
                    ],
                    [__plasmic_idx_0],
                    undefined ?? {},
                    child$Props
                  );
                  initializePlasmicStates(
                    $state,
                    [
                      {
                        name: "popoverCore[].open",
                        initFunc: ({ $props, $state, $queries }) => undefined
                      }
                    ],
                    [__plasmic_idx_0]
                  );
                  return (
                    <Popover
                      data-plasmic-name={"popoverCore"}
                      data-plasmic-override={overrides.popoverCore}
                      {...child$Props}
                    >
                      {(() => {
                        try {
                          return currentIndex === 0;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return true;
                          }
                          throw e;
                        }
                      })() ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ouXTe
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__uCtJt
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                    </Popover>
                  );
                })()}
              </Stack__>
            );
          })
        : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "checkbox",
    "to",
    "from",
    "popoverCore",
    "\u0631\u0648\u0632\u0647\u0627\u0647\u0641\u062a\u0647"
  ],
  checkbox: ["checkbox"],
  to: ["to"],
  from: ["from"],
  popoverCore: [
    "popoverCore",
    "\u0631\u0648\u0632\u0647\u0627\u0647\u0641\u062a\u0647"
  ],
  روزهاهفته: ["\u0631\u0648\u0632\u0647\u0627\u0647\u0641\u062a\u0647"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  checkbox: typeof Checkbox;
  to: typeof Select;
  from: typeof Select;
  popoverCore: typeof Popover;
  روزهاهفته: typeof روزهاهفته;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  Plasmicساعتار__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: Plasmicساعتار__VariantsArgs;
    args?: Plasmicساعتار__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<Plasmicساعتار__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      Plasmicساعتار__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: Plasmicساعتار__ArgProps,
          internalVariantPropNames: Plasmicساعتار__VariantProps
        }),
      [props, nodeName]
    );
    return Plasmicساعتار__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic\u0633\u0627\u0639\u062a\u0627\u0631";
  } else {
    func.displayName = `Plasmicساعتار.${nodeName}`;
  }
  return func;
}

export const Plasmicساعتار = Object.assign(
  // Top-level Plasmicساعتار renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    checkbox: makeNodeComponent("checkbox"),
    to: makeNodeComponent("to"),
    from: makeNodeComponent("from"),
    popoverCore: makeNodeComponent("popoverCore"),
    روزهاهفته: makeNodeComponent(
      "\u0631\u0648\u0632\u0647\u0627\u0647\u0641\u062a\u0647"
    ),

    // Metadata about props expected for Plasmicساعتار
    internalVariantProps: Plasmicساعتار__VariantProps,
    internalArgProps: Plasmicساعتار__ArgProps
  }
);

export default Plasmicساعتار;
/* prettier-ignore-end */
