// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rqmTJ9WSF4RQaQFCvo2iUX
import * as React from "react";
import { Fragment } from "@paziresh24/apps/drapp/fragment/designSystemGlobalContext"; // plasmic-import: IVhYCFf99ccR/codeComponent

export default function GlobalContextsProvider(props) {
  const { children, fragmentProps } = props;
  return (
    <Fragment
      {...fragmentProps}
      apiConfig={
        fragmentProps && "apiConfig" in fragmentProps
          ? fragmentProps.apiConfig
          : { withCredentials: true }
      }
      previewApiConfig={
        fragmentProps && "previewApiConfig" in fragmentProps
          ? fragmentProps.previewApiConfig
          : undefined
      }
    >
      {children}
    </Fragment>
  );
}
