// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxImportSource @plasmicapp/react-web-runtime */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rqmTJ9WSF4RQaQFCvo2iUX
// Component: -bo81HmjigXx
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_fragment_design_system_css from "../fragment_design_system/plasmic.module.css"; // plasmic-import: h9Dbk9ygddw7UVEq1NNhKi/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: rqmTJ9WSF4RQaQFCvo2iUX/projectcss
import sty from "./Plasmicدمهتجوزنسخه.module.css"; // plasmic-import: -bo81HmjigXx/css

export const Plasmicدمهتجوزنسخه__VariantProps = new Array();

export const Plasmicدمهتجوزنسخه__ArgProps = new Array();

const $$ = {};

function Plasmicدمهتجوزنسخه__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_fragment_design_system_css.plasmic_tokens,
        sty.root
      )}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: Plasmicدمهتجوزنسخه__ArgProps,
          internalVariantPropNames: Plasmicدمهتجوزنسخه__VariantProps
        }),
      [props, nodeName]
    );
    return Plasmicدمهتجوزنسخه__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName =
      "Plasmic\u062f\u0645\u0647\u062a\u062c\u0648\u0632\u0646\u0633\u062e\u0647";
  } else {
    func.displayName = `Plasmicدمهتجوزنسخه.${nodeName}`;
  }
  return func;
}

export const Plasmicدمهتجوزنسخه = Object.assign(
  // Top-level Plasmicدمهتجوزنسخه renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for Plasmicدمهتجوزنسخه
    internalVariantProps: Plasmicدمهتجوزنسخه__VariantProps,
    internalArgProps: Plasmicدمهتجوزنسخه__ArgProps
  }
);

export default Plasmicدمهتجوزنسخه;
/* prettier-ignore-end */
