// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  Plasmicدمهوضعتوزت,
  DefaultدمهوضعتوزتProps
} from "./plasmic/opium/Plasmic\u062F\u0645\u0647\u0648\u0636\u0639\u062A\u0648\u0632\u062A";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface دمهوضعتوزتProps extends Omit<DefaultدمهوضعتوزتProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultدمهوضعتوزتProps altogether and have
// total control over the props for your component.
export interface دمهوضعتوزتProps extends DefaultدمهوضعتوزتProps {}

function دمهوضعتوزت_(props: دمهوضعتوزتProps, ref: HTMLElementRefOf<"div">) {
  // Use Plasmicدمهوضعتوزت to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into Plasmicدمهوضعتوزت are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all دمهوضعتوزتProps here, but feel free
  // to do whatever works for you.

  return <Plasmicدمهوضعتوزت root={{ ref }} {...props} />;
}

const دمهوضعتوزت = React.forwardRef(دمهوضعتوزت_);
export default دمهوضعتوزت;
