// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  Plasmicساعتار,
  DefaultساعتارProps
} from "./plasmic/opium/Plasmic\u0633\u0627\u0639\u062A\u0627\u0631";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface ساعتارProps extends Omit<DefaultساعتارProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultساعتارProps altogether and have
// total control over the props for your component.
export interface ساعتارProps extends DefaultساعتارProps {}

function ساعتار_(props: ساعتارProps, ref: HTMLElementRefOf<"div">) {
  // Use Plasmicساعتار to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into Plasmicساعتار are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all ساعتارProps here, but feel free
  // to do whatever works for you.

  return <Plasmicساعتار root={{ ref }} {...props} />;
}

const ساعتار = React.forwardRef(ساعتار_);
export default ساعتار;
